AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label: 
          default: "VPC Selection"
        Parameters: 
          - pVpc
      -
        Label: 
          default: "Security Group Naming"
        Parameters: 
          - SGname
          - SGdesc
      -
        Label: 
          default: "Ingress Rule 1 [REQUIRED]"
        Parameters: 
          - pIngressRule1IpProtocol
          - pIngressRule1Port
          - pIngressRule1Cidr
      -
        Label: 
          default: "Ingress Rule 2"
        Parameters: 
          - pIngressRule2IpProtocol
          - pIngressRule2Port
          - pIngressRule2Cidr
      -
        Label: 
          default: "Ingress Rule 3"
        Parameters: 
          - pIngressRule3IpProtocol
          - pIngressRule3Port
          - pIngressRule3Cidr
      -
        Label: 
          default: "Ingress Rule 4"
        Parameters: 
          - pIngressRule4IpProtocol
          - pIngressRule4Port
          - pIngressRule4Cidr
      -
        Label: 
          default: "Ingress Rule 5"
        Parameters: 
          - pIngressRule5IpProtocol
          - pIngressRule5Port
          - pIngressRule5Cidr
      -
        Label: 
          default: "Egress Rule 1 [REQUIRED]"
        Parameters: 
          - pEgressRule1IpProtocol
          - pEgressRule1Port
          - pEgressRule1Cidr
      -
        Label: 
          default: "Egress Rule 2"
        Parameters: 
          - pEgressRule2IpProtocol
          - pEgressRule2Port
          - pEgressRule2Cidr
      -
        Label: 
          default: "Egress Rule 3"
        Parameters: 
          - pEgressRule3IpProtocol
          - pEgressRule3Port
          - pEgressRule3Cidr
      -
        Label: 
          default: "Egress Rule 4"
        Parameters: 
          - pEgressRule4IpProtocol
          - pEgressRule4Port
          - pEgressRule4Cidr
      -
        Label: 
          default: "Egress Rule 5"
        Parameters: 
          - pEgressRule5IpProtocol
          - pEgressRule5Port
          - pEgressRule5Cidr
    ParameterLabels: 
      pVpc: 
        default: "Select the ID of the VPC:"
      pIngressRule1IpProtocol:
        default: "Protocol"
      pIngressRule1Port:
        default: "Port"
      pIngressRule1Cidr:
        default: "CIDR"
      pIngressRule2IpProtocol:
        default: "Protocol"
      pIngressRule2Port:
        default: "Port"
      pIngressRule2Cidr:
        default: "CIDR"
      pIngressRule3IpProtocol:
        default: "Protocol"
      pIngressRule3Port:
        default: "Port"
      pIngressRule3Cidr:
        default: "CIDR"
     
