AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VpcId:
    Type: String
    Description: "ID of the VPC where the security group will be created"
  SGname:
    Type: String
    Description: "Name of the security group"
  SGdesc:
    Type: String
    Description: "Description of the security group"
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SGdesc
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Ref SGname
      SecurityGroupIngress:
        - CidrIp: "192.168.2.0/24"
          Description: "Zebra Printer ports communication from Akron, Dallas, and Canada"
          FromPort: 9100
          ToPort: 9100
          IpProtocol: "tcp"
        - CidrIp: "197.1.15.0/24"
          Description: "Zebra Printer ports communication from Akron, Dallas, and Canada"
          FromPort: 9100
          ToPort: 9100
          IpProtocol: "tcp"
        - CidrIp: "10.223.128.0/17"
          Description: "Zebra Printer ports communication from Akron, Dallas, and Canada"
          FromPort: 9100
          ToPort: 9100
          IpProtocol: "tcp"
        - CidrIp: "204.110.78.0/24"
          Description: "Dallas Subnet PING"
          FromPort: -1
          ToPort: -1
          IpProtocol: "icmp"
        - CidrIp: "192.168.2.0/24"
          Description: "Canada ICMP testing"
          FromPort: -1
          ToPort: -1
          IpProtocol: "icmp"
        - CidrIp: "197.1.15.0/24"
          Description: "Canada ICMP testing"
          FromPort: -1
          ToPort: -1
          IpProtocol: "icmp"
        - CidrIp: "10.8.10.0/24"
          Description: "Test"
          FromPort: 0
          ToPort: 65535
          IpProtocol: "-1"
        - CidrIp: "10.224.0.0/15"
          Description: "Zebra Printer ports communication from Akron, Dallas, and Canada"
          FromPort: 9100
          ToPort: 9100
          IpProtocol: "tcp"
        - CidrIp: "10.255.255.0/24"
          Description: "Zebra Printer ports communication from Akron, Dallas, and Canada"
          FromPort: 9100
          ToPort: 9100
          IpProtocol: "tcp"
        - CidrIp: "10.224.0.0/15"
          Description: "Dallas DC - RDP"
          FromPort: 3389
          ToPort: 3389
          IpProtocol: "tcp"
        - CidrIp: "10.240.0.0/12"
          Description: "Zebra Printer ports communication from Akron, Dallas, and Canada"
          FromPort: 9100
          ToPort: 9100
          IpProtocol: "tcp"
        - CidrIp: "197.1.14.128/25"
          Description: "Zebra Printer ports communication from Akron, Dallas, and Canada"
          FromPort: 9100
          ToPort: 9100
          IpProtocol: "tcp"
        - CidrIp: "10.241.74.20/32"
          Description: "ServiceNow Discovery Init Port - Eric Retherford 5/18/21"
          FromPort: 135
          ToPort: 135
          IpProtocol: "tcp"
        - CidrIp: "197.1.14.128/25"
          Description: "Canada ICMP testing"
          FromPort: -1
          ToPort: -1
          IpProtocol: "icmp"
        - CidrIp: "10.240.0.0/12"
          Description: "Akron DC - Ping"
          FromPort: -1
          ToPort: -1
          IpProtocol: "icmp"
        - CidrIp: "10.241.74.20/32"
          Description: "ServiceNow Discovery Range - Eric Retherford 5/18/21"
          FromPort: 49152
          ToPort: 65535
          IpProtocol: "tcp"
        - CidrIp: "10.240.0.0/12"
          Description: "EnCase from Akron"
          FromPort: 4445
          ToPort: 4445
          IpProtocol: "tcp"
        - CidrIp: "10.240.0.0/12"
          Description: "Akron DC - RDP"
          FromPort: 3389
          ToPort: 3389
          IpProtocol: "tcp"
        - CidrIp: "10.224.0.0/15"
          Description: "Dallas DC - Ping"
          FromPort: -1
          ToPort: -1
          IpProtocol: "icmp"
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "-1"
